# Generated by Django 3.2.7 on 2021-09-04 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='release',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Release date'),
        ),
    ]
